### ISSUE TITLE
client component for nextjs app router

### ISSUE THREAD

**Issue by zatakiya** [Byongho96/react-responsive-3d-carousel#12]
Using carousel on server components in nextjs app router throws error

Can you add "use client" at the top of files that uses client side hooks ? It will solve the error.

**Comment by Byongho96** [comment]
I've never thought about using components in Next.js before.
I'll test it with 'use client' statement, then let you know soon.

**Comment by Byongho96** [comment]
@zatakiya, I just tested the package on a NEXT.js application, and it worked well. It seems like I need to include the 'use client' statement in **your component** where you want to use the package, not in the library itself. I encountered a similar error when that 'use client' statement was missing.

![next](https://github.com/Byongho96/react-responsive-3d-carousel/assets/47059013/318bccb4-0393-44d0-b793-3c5c99ddf43b)

**Comment by Byongho96** [comment]
I tried, but the 'use client' statement is being ignored during the bundling process. It's probably because 'use client' is special syntax used in NEXT.js. For now, it's recommended to use it **within a client component.**

![bundling](https://github.com/Byongho96/react-responsive-3d-carousel/assets/47059013/b6060ba6-0ca5-4ee2-ab40-a3644139f18a)

Let me know if you find a solution or need further assistance.
