### ISSUE TITLE
I can't open a PR with a fork of repository

### ISSUE THREAD

**Issue by mdjfs** [Byongho96/react-responsive-3d-carousel#2]
Hi! Nice library! I add nice updates like select one item of the carousel and pause on hover the centered item. Here it is https://github.com/mdjfs/react-responsive-3d-carousel but i can't do a PR with the features. I don't know if is about repository privacy. Anyway, have a nice day !

**Comment by Byongho96** [comment]
Hi mdjfs,
First of all, I want to sincerely apologize. It's my first time creating an open-source project, and I didn't know how to manage it well. Above all, I never thought someone would leave an issue. I'm really, really sorry.

I've already updated the contributing guidelines. It turns out you need to fork the original repository, commit changes, and then contribute (pull request) back to the original repository.

I've already updated the contributing guidelines. It turns out you need to fork the original repository, commit changes, and then contribute (pull request) back to the original repository. I feel like such a novice for not realizing this earlier.

**Comment by Byongho96** [comment]
Also I checked the commit history by following the link you provided. It seems like a really useful and necessary feature! I appreciate you aligning with my code style.

However, I have a couple of suggestions for modifications. To avoid inconveniencing you, I'll write a bit here in advance.

First, `pause` is declared using `useState`, but since it's not related to re-rendering, it seems appropriate to declare it using `useRef`. Like this
```javascript
const pause = useRef(false);

const slidePrev = useCallback(() => {
  if (pause.current) return;
  // ...
}, [length, pause]);
```

Also, `selectable` and `onClickSelected` seem to be interrelated. I think it would be beneficial to separate them, making each prop independent. So, I suggest splitting them as follows:
```javascript
selectable: boolean // whether curIndex can be updated by select (click) event
onClickItem: (index: number) => void // callback function when carousel item is clicked
onClickSelectedItem: (index: number) => void // callback function when the selected carousel item is clicked

const selectSlide = useCallback(
  (index: number) => {
    if (selectable) setCurIndex(index);
    if (onClickItem) onClickItem(index);
    if (curIndex === index && onClickSelectedItem) onClickSelectedItem(index);
  },
  [curIndex, selectable, onClickSelected]
);
```

Finally, it seems that `selectSlide`, `startPause`, and `releasePause` might not need to be memoized as `useCallback` functions. This is because they have `curIndex` in their dependency arrays, which is frequently updated
```javascript
const startPause = (index: number) => {
  if (pauseOnHover && curIndex === index) {
    pause.current = true
  }
}
```
Feel free to let me know your thoughts or if there are any further changes you'd like. Thanks!

**Comment by mdjfs** [comment]
Hello @Byongho96 how are you? Don't worry. I know how it feels. This library is a great work to start without a lot of configuration and zero-dependency. 

About the refs, i don't know about that, for me is the first time I see it. But. I understand the purpose, we don't really need a re-render or state update. If the useRef changes the local var without updating the component, nice! And to fire events with any slide clicked is perfect. Go ahead with that! 

Let me know if you need something to help you (i can create a PR with the suggestions if you need). And thanks for check the feature request!

**Comment by Byongho96** [comment]
I would be **really grateful** if you could create a pull request. After all, you're my first contributor! It's fine to submit the pull request with the existing code. The comments I left above in advance were due to my delayed response.

**Comment by mdjfs** [comment]
Thank you man! Tomorrow I have some time yo check that and send the PR

**Comment by Byongho96** [comment]
Thank you, I'll check it as soon as you upload it.

**Comment by mdjfs** [comment]
Hi! I did the changes, but i can't open the PR across forks, check it:

![image](https://github.com/Byongho96/react-responsive-3d-carousel/assets/56895143/68a24e65-d005-4bb3-9a08-2c9dcedec3eb)
![image](https://github.com/Byongho96/react-responsive-3d-carousel/assets/56895143/96c7648b-4ef2-4e0b-badd-f2766ad65e0a)

I can't see my repos here, i don't know if is a github problem or permissions problem

**Comment by Byongho96** [comment]
I didn't provide enough explanation. I created a sub-account called 'bl3403' to explain. Assume that bl3403 is you, and read the following.

1. First of all, you need to fork the existing repository 'Byongho96/react-responsive-3d-carousel' into your repository. 
![fork](https://github.com/Byongho96/react-responsive-3d-carousel/assets/47059013/2efa88ce-dfa1-476d-8f68-c1865a2a8f34)

2. When forking, you need to choose a repository name. Since you already have 'react-responsive-3d-carousel' in your account, you either need to delete the existing one or choose a different name when forking.
![create fork](https://github.com/Byongho96/react-responsive-3d-carousel/assets/47059013/e056c4e3-a97c-41f8-a44d-1c5ccb3b9251)

3. When the fork is successful, the repository typically displays information about where it was forked from. In this case, it would show 'forked from Byongho96/react-responsive-3d-carousel.'
![forked repository](https://github.com/Byongho96/react-responsive-3d-carousel/assets/47059013/04c3a3ca-59b8-4272-a0e2-33666800f57a)

4. Clone the forked repository to the local, then commit and push the changes.

5. And click on the "Contribute" button to create a pull request.
![contribute](https://github.com/Byongho96/react-responsive-3d-carousel/assets/47059013/44c9fedf-af3d-48a8-9e83-566a6fcc2acf)

5. In the end, you're creating a pull request from **the forked repository** to **the original repository**, as illustrated in the diagram below.

**Comment by mdjfs** [comment]
Thanks for the full tuto! very helpful, sorry for the time wasted doing the tuto lol
