### ISSUE TITLE
Documentation improvement: A reminder to import images

### ISSUE THREAD

**Issue by SoftDevLiz** [Byongho96/react-responsive-3d-carousel#34]
Hi! I am using this carousel for my portfolio. I got stuck trying to change the images because I forgot that I needed to import the images at the top of the file when using React. It may be common knowledge but as a junior you forget little things like that.

<img width="421" alt="Screenshot 2024-11-17 at 12 25 06" src="https://github.com/user-attachments/assets/5d6d6132-14a7-487d-af01-e9930e609eca">

May I make my first open source contribution by adding in a reminder in the docs to import your images with React? 

Thank you,

Liz.

**Comment by Byongho96** [comment]
@SoftDevLiz  Thank you for taking an interest in the library!
However, the suggested feature doesn't seem necessary.

This is because it's not mandatory to import the image.
If the image source is part of the React project and managed by the bundler such as Webpack, importing it as shown in the screenshot you shared is valid. Most React projects work that way, but this behavior can vary depending on the bundler configuration.

Since importing an image ultimately resolves to a URL path, all you really need is the image URL. For instance, you can simply write:
```jsx
<img src="https://image.url" />
```
Still, I appreciate your thoughtful feedback! 😊
